#!/bin/sh
cd /workspace/api

# Load environment variables from .env
if [ -f /workspace/.env ]; then
    set -a
    . /workspace/.env
    set +a
fi

# Redirect stdout and stderr to log file
exec /usr/local/bin/gunicorn -c gunicorn_conf.py main:app \
  >> /workspace/logs/gunicorn.log 2>&1
