#!/bin/sh
cd /workspace/api

# Load environment variables from .env
if [ -f /workspace/.env ]; then
    set -a
    . /workspace/.env
    set +a
fi

exec /usr/local/bin/gunicorn -c gunicorn_conf.py main:app
