#!/bin/sh
cd /app/api
exec gunicorn main:app \
  --bind 127.0.0.1:8000 \
  --workers ${GUNICORN_WORKERS:-4} \
  --worker-class uvicorn.workers.UvicornWorker \
  --access-logfile /app/logs/gunicorn-access.log \
  --error-logfile /app/logs/gunicorn-error.log \
  --log-level ${LOG_LEVEL:-info}
