#!/bin/sh
# Load environment variables from .env
if [ -f /workspace/.env ]; then
  set -a
  . /workspace/.env
  set +a
fi
cd /workspace/services/mod_status
# Redirect stdout and stderr to log file
exec ./bin/status >> /workspace/logs/mod_status.log 2>&1
